title: "Hexlet Guides"
email: support@hexlet.io
timezone: UTC
baseurl: ""
repository: Hexlet/hexletguides.github.io

tagline: Гайды
description: |
  Полезные статьи и гайды для разработчиков

# twitter:
#   username: HexletHQ
#   card: summary

social:
  links:
    - https://www.instagram.com/hexlethq/
    - https://www.facebook.com/Hexlet/
    - https://twitter.com/HexletHQ

permalink: "/:title/"
logo: 'assets/images/hexlet_logo.png'
favicon: 'assets/images/favicons/favicon-128.png'
author: Kirill Mokevnin
# paginate: 30
disqus: hexlet-guides
locale: ru_RU
lang: ru_RU

# toc:
#   min_level: 1
#   max_level: 1
#   list_class: 'list-unstyled p-3 bg-light'

# feed_items: 10
# feed_update_period: daily
# feed_update_frequency: 1

markdown: kramdown
# commonmark:
#   options: ["SMART", "FOOTNOTES"]
#   extensions: ["strikethrough", "autolink", "table"]
kramdown:
  input: GFM
  # default_lang: html
  syntax_highlighter_opts:
    css_class: 'syntax'
    # disable: true

highlighter: rouge

sass:
  # sass_dir: _sass
  load_paths:
    - _sass
    - node_modules
  # style: :compressed

# ganalytics: GTM-KMJ8HKG

# Plugins
plugins:
  # - jekyll-paginate
  - jekyll-sitemap
  # - jekyll-commonmark
  - jekyll-include-cache
  - jekyll-feed
  # - jekyll-toc
  - jekyll-seo-tag
  # - jekyll-archives
  - jekyll-github-metadata
  - amp-jekyll

defaults:

  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

  # - scope:
  #     path: ""
  #     type: "posts"
  #   values:
  #     toc: true

  - scope:
      path: yandex_d1b9fafe78d3bf70.html
    values:
      sitemap: false
